display ustrregexm("`", "^`{5}")
display ustrregexm("``", "^`{5}")
display ustrregexm("```", "^`{5}")
display ustrregexm("````", "^`{5}")
display ustrregexm("`````", "^`{5}")

display ustrregexm("`", "^`{3,5}")
display ustrregexm("``", "^`{3,5}")
display ustrregexm("```", "^`{3,5}")
display ustrregexm("````", "^`{3,5}")
display ustrregexm("`````", "^`{3,5}")
